[package]
name = "actix-youtube"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[dependencies]
actix-web = "4.11.0"

[lints.clippy]
all="deny"

[profile.dev]
debug = true

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
